development:
      host: remotemysql.com
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: root
      password: foradian

test: &test
      host: remotemysql.com
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: remotemysql.com
      adapter: mysql
      database: fAXatDZnAv
      port: 3306
      username: fAXatDZnAv
      password: WuXtvIHfW2
cucumber:
  <<: *test
